# Generated by Django 3.2.9 on 2021-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionfee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
